name: Coverage
on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    name: Coverage
    runs-on: windows-latest
    env:
      VCPKG_DEFAULT_TRIPLET: x64-windows-release
      VCPKG_ROOT: ${{ github.workspace }}/vcpkg

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install OpenCppCoverage # Needed to generate coverage
        run: |
          curl -L https://github.com/OpenCppCoverage/OpenCppCoverage/releases/download/release-0.9.7.0/OpenCppCoverageSetup-x64-0.9.7.0.exe -o OpenCppCoverageSetup.exe
          Start-Process -FilePath .\OpenCppCoverageSetup.exe -ArgumentList "/SUPRESSMSGBOXES /NORESTART /VERYSILENT" -NoNewWindow -Wait

      - name: Run build-wrapper
        run: |
          New-Item -ItemType directory -Path build
          cmake -S . -B build -DBUILD_TESTS=ON -DCMAKE_BUILD_TYPE=RelWithDebInfo
          cmake --build build/ --config RelWithDebInfo
      
      - name: Run tests with coverage
        run: |
          cd build/test
          &"C:\Program Files\OpenCppCoverage\OpenCppCoverage.exe" --cover_children --excluded_sources vctools --excluded_sources test --excluded_sources "Program Files" --excluded_sources ExternalAPIs "--export_type=cobertura:cobertura.xml" -- ctest -j4 -C RelWithDebInfo
      - name: Print XML file content
        run: |
          cat build/test/cobertura.xml
      
      - name: Code Coverage Report
        uses: clearlyip/code-coverage-report-action@v4
        with:
            filename: build/test/cobertura.xml
            badge: true
            overall_coverage_fail_threshold: 10

